export enum UsualBlockTypeEnum {
  METHODS_LIST = 'METHODS_LIST',
  LONG = 'LONG',
  MONEY_BACK = 'MONEY_BACK',
  MONEY_BACK2 = 'MONEY_BACK2',
  REVIEWS_CRM = 'REVIEWS_CRM',
  WHY_CRM = 'WHY_CRM',
  HOW_CRM = 'HOW_CRM',
}
